# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load_data": "eda_ref_amendements.ipynb",
         "amdt": "02_word_count.ipynb",
         "build_word_cloud": "02_word_count.ipynb",
         "display_distinct": "eda_ref_amendements.ipynb"}

modules = ["word_count.py",
           "eda_ref.py"]

doc_url = "https://leximpact.github.io/etudes-amendements/"

git_url = "https://github.com/leximpact/etudes-amendements/tree/main/"

def custom_doc_links(name): return None
